export default [
  {
    login: "caothethang",
    id: 55690194,
    node_id: "MDQ6VXNlcjU1NjkwMTk0",
    avatar_url: "https://avatars.githubusercontent.com/u/55690194?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/caothethang",
    html_url: "https://github.com/caothethang",
    followers_url: "https://api.github.com/users/caothethang/followers",
    following_url:
      "https://api.github.com/users/caothethang/following{/other_user}",
    gists_url: "https://api.github.com/users/caothethang/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/caothethang/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/caothethang/subscriptions",
    organizations_url: "https://api.github.com/users/caothethang/orgs",
    repos_url: "https://api.github.com/users/caothethang/repos",
    events_url: "https://api.github.com/users/caothethang/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/caothethang/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "ThanhThanh189",
    id: 65250139,
    node_id: "MDQ6VXNlcjY1MjUwMTM5",
    avatar_url: "https://avatars.githubusercontent.com/u/65250139?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/ThanhThanh189",
    html_url: "https://github.com/ThanhThanh189",
    followers_url: "https://api.github.com/users/ThanhThanh189/followers",
    following_url:
      "https://api.github.com/users/ThanhThanh189/following{/other_user}",
    gists_url: "https://api.github.com/users/ThanhThanh189/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/ThanhThanh189/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/ThanhThanh189/subscriptions",
    organizations_url: "https://api.github.com/users/ThanhThanh189/orgs",
    repos_url: "https://api.github.com/users/ThanhThanh189/repos",
    events_url: "https://api.github.com/users/ThanhThanh189/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/ThanhThanh189/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "tana142",
    id: 69696606,
    node_id: "MDQ6VXNlcjY5Njk2NjA2",
    avatar_url: "https://avatars.githubusercontent.com/u/69696606?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/tana142",
    html_url: "https://github.com/tana142",
    followers_url: "https://api.github.com/users/tana142/followers",
    following_url:
      "https://api.github.com/users/tana142/following{/other_user}",
    gists_url: "https://api.github.com/users/tana142/gists{/gist_id}",
    starred_url: "https://api.github.com/users/tana142/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/tana142/subscriptions",
    organizations_url: "https://api.github.com/users/tana142/orgs",
    repos_url: "https://api.github.com/users/tana142/repos",
    events_url: "https://api.github.com/users/tana142/events{/privacy}",
    received_events_url: "https://api.github.com/users/tana142/received_events",
    type: "User",
    site_admin: false,
  },
];
