export default {
  login: "sonhellu",
  id: 55440158,
  node_id: "MDQ6VXNlcjU1NDQwMTU4",
  avatar_url: "https://avatars.githubusercontent.com/u/55440158?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/sonhellu",
  html_url: "https://github.com/sonhellu",
  followers_url: "https://api.github.com/users/sonhellu/followers",
  following_url: "https://api.github.com/users/sonhellu/following{/other_user}",
  gists_url: "https://api.github.com/users/sonhellu/gists{/gist_id}",
  starred_url: "https://api.github.com/users/sonhellu/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/sonhellu/subscriptions",
  organizations_url: "https://api.github.com/users/sonhellu/orgs",
  repos_url: "https://api.github.com/users/sonhellu/repos",
  events_url: "https://api.github.com/users/sonhellu/events{/privacy}",
  received_events_url: "https://api.github.com/users/sonhellu/received_events",
  type: "User",
  site_admin: false,
  name: "Nguyễn Văn Sơn",
  company: "Đại học Công Nghiệp Hà Nội",
  blog: "https://www.facebook.com/sonhelluu/",
  location: "Hà Nội",
  email: null,
  hireable: null,
  bio: "@sonhellu",
  twitter_username: "HelluSon",
  public_repos: 5,
  public_gists: 0,
  followers: 3,
  following: 4,
  created_at: "2019-09-17T10:47:05Z",
  updated_at: "2021-06-24T15:59:38Z",
};
